apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
  namespace: wisecow
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:region:account:certificate/certificate-id
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  type: LoadBalancer
  selector:
    app: wisecow
  ports:
  - protocol: TCP
    port: 443
    targetPort: 3000
